version: '3.8'
services:
  sql-training:
    build: .
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=training_db
    ports:
      - 3306:3306
